### ISSUE TITLE
speed of PoseFix

### ISSUE THREAD

**Issue by thancaocuong** [mks0601/PoseFix_RELEASE#16]
thank you for that awesome release. But can you tell me how to calculate speed per one image when testing?

**Comment by mks0601** [comment]
can you clarify what you want to know? do you want to know how to measure seconds in python?

**Comment by thancaocuong** [comment]
I want to calculate FPS when testing on COCO val2017. I ran your test script on COCO val2017 and got same AR and AP as SOTA.  But the total time was 7h27m54s. I ran on single GTX 1080 TI. 
I don't know why it took so long.

**Comment by mks0601** [comment]
54th line of `test.py` is start of each cropped image's testing. You should start to measure second at line 55 and ends at line 128. The indentation level of line 55 and 128 should be the same. I also feel that running time of PoseFix is slow. I think that is because input is not RGB, but RGB + heatmap. As heatmap is very large tensor (384x288xjoint_num), it will take time.

**Comment by thancaocuong** [comment]
thank you so much. I will try this ^^
